import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import Providers from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}
          <Toaster/>
        </Providers>
      </body>
    </html>
  );
}
